### ISSUE TITLE
Would you please provide the codes/models of other trackers?

### ISSUE THREAD

**Issue by dyhBUPT** [wudongming97/RMOT#1]
Hi, thanks for your excellent work!

Would you please provide the codes/models of other trackers?
For example, the detection(referent) results from FairMOT with integrated cross-modal fusion module.

Thanks~

**Comment by wudongming97** [comment]
Here are FairMOT results from Google Drive (https://drive.google.com/file/d/1bPfe8dU_dcYZicuoy67CaasI_YMj45Ic/view?usp=sharing).

**Comment by wudongming97** [comment]
@xiaocc612 Sorry. I'm not sure I can find them due to the long time. Please refer to the data from the manuscript.
