### ISSUE TITLE
Some questions regarding experiments and code.

### ISSUE THREAD

**Issue by xiaocc612** [wudongming97/RMOT#11]
Hello,
Thanks for your excellent work!

1. The HOTA in Results in this repository is 2.5% (38.06%-35.54%) higher than that reported in the paper,better how was this result obtained? Is this better result obtained by tuning the parameters?
2. Does "Language as query" in Table 3(a) of the article mean that Q in Eq. (1) is obtained by transforming linguistic features while K is obtained by visual features?

Thanks~

**Comment by wudongming97** [comment]
Hi,

1. Yes. We changed the sample interval to 1 during training, which has 2.5% gain (mainly influencing AssA). This is because KITTI has been downsampled and two adjacent frames have larger differences.
2. Yes. You are correct!

**Comment by wudongming97** [comment]
The ablation experiment in MOTR is evaluated on MOT17, whose frames are not downsampled, so increasing 'sampler_lengths'  brings performance gain. However, the frames of KITTI are downsampled. 

In a word, you need to tune 'sampler_lengths' according to the frame rate of the specific dataset.

**Comment by wudongming97** [comment]
Sorry for misunderstanding you. I didn't try to increase the "sampler_lengths" in our experiments. Maybe you can try this setting.
