### ISSUE TITLE
Some questions about labels_with_ids.

### ISSUE THREAD

**Issue by xiaocc612** [wudongming97/RMOT#12]
Hi,
    From reading the article and the code, I know that the txt files in labels_with_ids contain the track_id and bbox of the object in the corresponding frame, and I would like to know how these files are generated (what rules are followed?) ? It seems that there is not a one-to-one correspondence with the [KITTI MOT labels](https://www.cvlibs.net/datasets/kitti/eval_tracking.php).
   Thanks.

**Comment by wudongming97** [comment]
We re-implement the code from [FairMOT](https://github.com/ifzhang/FairMOT) to generate track_id and box. I strongly recommend using our  labels_with_ids file instead of re-generating it.

**Comment by wudongming97** [comment]
The label_with_ids (track ID and bbox) is generated from official annotations. The script is from FairMOT.

**Comment by wudongming97** [comment]
Okay. I will find it.

**Comment by wudongming97** [comment]
https://github.com/wudongming97/RMOT/blob/master/tools/gen_track_id_from_kitti.py

It is updated.

**Comment by wudongming97** [comment]
Hi,
Please notice our warning https://github.com/wudongming97/RMOT/issues/12#issuecomment-1705348641 .
We also update the warning in README.
