### ISSUE TITLE
Problems encountered during testing

### ISSUE THREAD

**Issue by mengmimi** [wudongming97/RMOT#13]
Hello, I used the command you provided to test：
python inference.py --meta_arch rmot --dataset_file e2e_rmot --epoch 200 --with_box_refine --lr_drop 100 --lr 2e-4 --lr_backbone 2e-5 --batch_size 1 --sample_mode random_interval --sample_interval 1 --sampler_steps 50 90 150 --samp
ler_lengths 2 3 4 5 --update_query_pos --merger_dropout 0 -lt/checkpoint0099.pth --output_dir exps/default --visualization

but the following problem occurred during runtime：
raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/data/wudongming/FairMOT/src/roberta_base/'. Use `repo_type` argument if needed.

 I wonder which part of the command line needs to be modified?

**Comment by mengmimi** [comment]
By the way,I did not see the path"exps/default/hcheckpoint0099.pth"

**Comment by wudongming97** [comment]
> Hello, I used the command you provided to test： python inference.py --meta_arch rmot --dataset_file e2e_rmot --epoch 200 --with_box_refine --lr_drop 100 --lr 2e-4 --lr_backbone 2e-5 --batch_size 1 --sample_mode random_interval --sample_interval 1 --sampler_steps 50 90 150 --samp ler_lengths 2 3 4 5 --update_query_pos --merger_dropout 0 -lt/checkpoint0099.pth --output_dir exps/default --visualization
> 
> but the following problem occurred during runtime： raise HFValidationError( huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/data/wudongming/FairMOT/src/roberta_base/'. Use `repo_type` argument if needed.
> 
> I wonder which part of the command line needs to be modified?

The error comes from https://github.com/wudongming97/RMOT/blob/master/models/transrmot.py#L476-L479 . Please follow README.md to download the checkpoint of ReBERTa from Huggingface.
