### ISSUE TITLE
Unable to run the RMOT model due ot lack of MSDA model 

### ISSUE THREAD

**Issue by Everloom-129** [wudongming97/RMOT#16]
Hello developer team, thank you for this noval work. When I am trying to do reproduction work on it, I met some problems. Here is the issue:
- I have follow the readme of https://github.com/fundamentalvision/Deformable-DETR, step by step. 
- I have installed and run the Roberta model from Hugging face
- I have download the checkpoint, and store it in `exps/default/checkpoint0099.pth `
- I am trying to run `sh configs/r50_rmot_test.sh`, and it says this:

```
(deformable_detr) root@tony:~/449_RMOT$ pip install MultiScaleDeformableAttention
  File "/root/449_RMOT/models/ops/functions/ms_deform_attn_func.py", line 21, in <module>
    import MultiScaleDeformableAttention as MSDA
ImportError: /root/miniconda3/envs/deformable_detr/lib/python3.7/site-packages/MultiScaleDeformableAttention-1.0-py3.7-linux-x86_64.egg/MultiScaleDeformableAttention.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceISt7complexIdEEEPKNS_6detail12TypeMetaDataEv
(deformable_detr) root@tony:~/449_RMOT$ 
```

I tried to solve it with GPT, but can not progress. Could you instruct me on where is the possible problem? For instance, what is this MSDA model and how should I download it?

```(deformable_detr) root@tony:~/449_RMOT$ pip install MultiScaleDeformableAttention
Looking in indexes: http://mirrors.aliyun.com/pypi/simple
Requirement already satisfied: MultiScaleDeformableAttention in /root/miniconda3/envs/deformable_detr/lib/python3.7/site-packages/MultiScaleDeformableAttention-1.0-py3.7-linux-x86_64.egg (1.0)
```

My pip said it has downloaded it already

**Comment by wudongming97** [comment]
> Hello developer team, thank you for this noval work. When I am trying to do reproduction work on it, I met some problems. Here is the issue:
> 
> * I have follow the readme of https://github.com/fundamentalvision/Deformable-DETR, step by step.
> * I have installed and run the Roberta model from Hugging face
> * I have download the checkpoint, and store it in `exps/default/checkpoint0099.pth `
> * I am trying to run `sh configs/r50_rmot_test.sh`, and it says this:
> 
> ```
> (deformable_detr) root@tony:~/449_RMOT$ pip install MultiScaleDeformableAttention
>   File "/root/449_RMOT/models/ops/functions/ms_deform_attn_func.py", line 21, in <module>
>     import MultiScaleDeformableAttention as MSDA
> ImportError: /root/miniconda3/envs/deformable_detr/lib/python3.7/site-packages/MultiScaleDeformableAttention-1.0-py3.7-linux-x86_64.egg/MultiScaleDeformableAttention.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceISt7complexIdEEEPKNS_6detail12TypeMetaDataEv
> (deformable_detr) root@tony:~/449_RMOT$ 
> ```
> 
> I tried to solve it with GPT, but can not progress. Could you instruct me on where is the possible problem? For instance, what is this MSDA model and how should I download it?
> 
> ```
> Looking in indexes: http://mirrors.aliyun.com/pypi/simple
> Requirement already satisfied: MultiScaleDeformableAttention in /root/miniconda3/envs/deformable_detr/lib/python3.7/site-packages/MultiScaleDeformableAttention-1.0-py3.7-linux-x86_64.egg (1.0)
> ```
> 
> My pip said it has downloaded it already


MultiScaleDeformableAttention should be complied with according to the instruction of Deformable DETR. Did you finish it?

**Comment by Everloom-129** [comment]
I solved it, I used to config the MSDA correctly, but after then another part of installation upgrade my torch and torchvision, which break the previous MSDA build.

## Solution is to remake the rmot project again in another clone
