### ISSUE TITLE
format explanation for the grounding annotation file

### ISSUE THREAD

**Issue by peiwang062** [wudongming97/RMOT#4]
any explanation or instruction for how to understand the format of the annotation files, `expression` and `labels_with_ids`?
how to link each other.

**Comment by wudongming97** [comment]
Each expression corresponds to multiple frames, each frame containing multiple labels_with_ids.

Sorry for the confusion, and we will update the details.

**Comment by peiwang062** [comment]
Thanks for the reply!
I still have no idea where to start. For example, for an expression, black-cars-in-right.json, how can I find its corresponding image and associated bbox?

**Comment by wudongming97** [comment]
When you open a JSON file, its corresponding images can be found in terms of its folder name.
Our JSON file have only corresponding ids, so the corresponding box can be seen from 'label_with_ids'.
