### ISSUE TITLE
More detail about how to run your work

### ISSUE THREAD

**Issue by BelieveF** [wudongming97/RMOT#6]
Hi, your work is amazing, can you provide more details on how to replicate your work? For example, I want to know where can get the file：/data/wudongming/FairMOT/SRC/roberta_base /.I would appreciate your reply

**Comment by wudongming97** [comment]
You can use https://github.com/wudongming97/RMOT/blob/master/models/transrmot.py#L472 and https://github.com/wudongming97/RMOT/blob/master/models/transrmot.py#L473 to this line.

Or you can load all files from https://huggingface.co/roberta-base/tree/main

**Comment by BelieveF** [comment]
Thank you for your reply. I have successfully reproduced your project, and the score of my reproduction result is attached. If you are interested, you can check it. Thank you for your work.
| |
13082752213
|
|
***@***.***
|
---- Replied Message ----
| From | Dongming ***@***.***> |
| Date | 7/13/2023 16:40 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [wudongming97/RMOT] More detail about how to run your work (Issue #6) |

Closed #6 as completed.

**Comment by wudongming97** [comment]
I am very welcome if you can release your reproduction result!
