### ISSUE TITLE
The pretrained Deformable DETR model and KITTI link

### ISSUE THREAD

**Issue by Spritea** [wudongming97/RMOT#7]
Hi, thanks for your great work!

About the pretrained Deformable DETR model used in training, could you specify which one is used in your paper, since there are several versions provided in the [repo](https://github.com/fundamentalvision/Deformable-DETR), and each has different performances on COCO.

Also, for kitti images, I guess the it shoud be the link marked below, is that right?

![kitti_link](https://github.com/wudongming97/RMOT/assets/22995173/af21e2de-7619-463b-916b-aee03ee5ce61)

**Comment by BelieveF** [comment]
Hello, I am also confused about your question. I saw that in the comments under the MOTR project, the author replied about pretrained Deformable DETR model used in training. We can give it a try. In addition, do you know the author the link of the project: / data/wudongming/FairMOT/SRC/roberta_base, on behalf of what? If you are interested, we can discuss more details about the revival of this project.

**Comment by GuangtaoLyu** [comment]
I have the same question. and I didn't reproduce the same evaluation metric.

**Comment by wudongming97** [comment]
> Hi, thanks for your great work!
> 
> About the pretrained Deformable DETR model used in training, could you specify which one is used in your paper, since there are several versions provided in the [repo](https://github.com/fundamentalvision/Deformable-DETR), and each has different performances on COCO.
> 
> Also, for kitti images, I guess the it shoud be the link marked below, is that right?
> 
> ![kitti_link](https://user-images.githubusercontent.com/22995173/251807816-af21e2de-7619-463b-916b-aee03ee5ce61.png)

The version of COCO-pretrained model is '+ iterative bounding box refinement' 

About KITTI images, I am sorry for forgetting their link.

**Comment by KainingYing** [comment]
> @Spritea @wudongming97 ![image](https://private-user-images.githubusercontent.com/44572048/315286416-991b7a5a-4c89-4744-90cf-df28b124bc36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2ODgwNzgsIm5iZiI6MTcyMDY4Nzc3OCwicGF0aCI6Ii80NDU3MjA0OC8zMTUyODY0MTYtOTkxYjdhNWEtNGM4OS00NzQ0LTkwY2YtZGYyOGIxMjRiYzM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDA4NDkzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkOWIwOWI0YWRhYjZkYjQ0OWVmNDBiYWQ3N2QzOWQzYTFiMGRiODQ1OWFlOGQ1YWY5MjdmZjhjMTNmYjI4ZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-XRGAkeB2Oq1ac7pSnnsgygnRJdRyGqcNWwwbEHzMF0) After downloading the KITTI dataset indicated in the diagram, the image_2 folder contains images numbered sequentially from 000000.png to 007480.png. Unlike the labels_with_ids folder, there are no subfolders like 0000-0020. Could you provide a solution for the training error 'FileNotFoundError: [Errno 2] No such file or directory: 'datasets/refer-kitti/KITTI/training/image_02/0020/000704.png'?

Same problem! have you solved it?

**Comment by KainingYing** [comment]
I found the download [link](https://www.kaggle.com/datasets/quanhu/kitti-object-tracking-left-color) which matchs this formation. Hope it helps.
